use website;

CREATE TABLE posts (
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  author VARCHAR(255),
  post LONGTEXT,
  dateposted VARCHAR(255)
);

CREATE TABLE events (
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  dateposted VARCHAR(255),
  details LONGTEXT
);
